import type { DashboardMetricsResponse } from '@/types/dashboard'

export function dashboardFixture(): DashboardMetricsResponse {
  return {
    period: 'month',
    userMetrics: {
      activeUsersToday: 1,
      activeUsersYesterday: 1,
      activeUsersLastWeek: 1,
      activeUsersLastMonth: 1,
      registeredToday: 1,
      registeredYesterday: 1,
      registeredThisWeek: 1,
      registeredLastWeek: 1,
      registeredThisMonth: 1,
      registeredLastMonth: 1,
      totalUsers: 1,
      totalGuestSessions: 1,
      guestSessionsToday: 1,
      guestSessionsLastWeek: 1,
      guestSessionsLastMonth: 1,
      guestToRegisteredCount: 1,
      guestToRegisteredPercentage: 1,
      returnedOnceCount: 1,
      returnedOncePercentage: 1,
      returnedMultipleCount: 1,
      returnedMultiplePercentage: 1,
      returningUsers: 1,
      returningUsersTotal: 1,
      signupSourceBreakdown: {
        google: 12,
        guykoren: 5,
        direct: 3,
        other: 1,
        unknown: 4,
      },
    },
    monthlySignups: [],
    contentCounts: { courses: 1, lessons: 1, exercises: 1, formulaSheets: 1, prompts: 1 },
    engagement: {
      avgTimeSpentMinutes: 1,
      medianTimeSpentMinutes: 1,
      stdDevTimeSpentMinutes: 1,
      courseEnrollments: [],
      usersPerCourse: [],
      topLessons: [],
      sessionTimeByLessonType: { learning: null, practice: null, exam: null },
      featureUsage: {
        questionsAsked: 1,
        conversationsStarted: 1,
        lessonsCompleted: 1,
        exercisesAttempted: 1,
        exercisesCompleted: 1,
      },
      lessonTypeUsage: { learning: 1, practice: 1, exam: 1 },
    },
    revenueMetrics: {
      totalRevenueAgorot: { ILS: 1 },
      refundedAgorot: 0,
      failedAgorot: 0,
      transactionCount: 1,
      successRate: 100,
      topProducts: [],
    },
    tokenMetrics: {
      totalTokensToday: 1,
      totalTokensThisMonth: 1,
      totalTokensThisYear: 1,
      avgTokensPerUserThisMonth: 1,
      avgTokensPerLessonThisMonth: 1,
      topLessons: [],
      topUsers: [],
    },
  }
}
